# Generated by Django 2.0.6 on 2018-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(),
        ),
    ]
