# Generated by Django 2.0.6 on 2018-07-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_extend_career_type_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(null=True, blank=True),
        ),
    ]
