# Generated by Django 2.0.6 on 2018-07-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_career_end_date_as_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='career',
            name='type',
            field=models.CharField(choices=[('WRK', 'Work'), ('EDU', 'Education'), ('CRT', 'Certificate'), ('OTH', 'Other')], max_length=3),
        ),
    ]
