# Generated by Django 2.0.6 on 2018-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_unify_career_with_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=65535)),
                ('type', models.CharField(choices=[('CONTENT', 'Content'), ('TITLE', 'Title')], max_length=10)),
                ('display_order', models.IntegerField()),
            ],
        ),
    ]
