# Generated by Django 2.0.6 on 2018-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_create_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='page_name',
            field=models.CharField(choices=[(('HOME',), 'Home'), ('RESUME', 'Title')], max_length=6, null=True),
        ),
    ]
