# Generated by Django 2.0.6 on 2018-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_page_name_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_name',
            field=models.CharField(choices=[(('HOME',), 'Home'), ('RESUME', 'Title'), ('PROJECTS', 'Projects')], max_length=9, null=True),
        ),
    ]
