# Generated by Django 2.0.6 on 2018-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_page_fix_choices_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='type',
            field=models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('certificates', 'Certificate'), ('other', 'Other')], max_length=12),
        ),
    ]
