# Generated by Django 2.0.6 on 2018-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_new_career_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='page', to='backend.PageContent'),
        ),
    ]
