# Generated by Django 2.0.6 on 2018-11-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_added_videomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageheader',
            name='image',
        ),
    ]
