# Generated by Django 2.0.6 on 2018-11-29 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_pageheader_relation_to_image_foreign_to_generic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='header',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageheader',
            name='page',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Page'),
            preserve_default=False,
        ),
    ]
