# Generated by Django 2.0.6 on 2018-11-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_page_rework_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='backend.Page'),
        ),
        migrations.AlterField(
            model_name='pageheader',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='backend.Page'),
        ),
        migrations.AlterField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(null=True, related_name='projects', to='backend.Event'),
        ),
    ]
